version: '2'

services:

  # Postgres ( db for Django )
  db:
    image: randyp/rpi-postgres
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5433"

  # Redis
  redis:
    image: w1mvy/raspberry-redis
    hostname: redis


  # RabbitMQ
  rabbit:
    hostname: rabbit
    build:
      context: .
      dockerfile: DockerfileMQ_Rpi
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # debugging
      - "15672:15672"  # rabbitmq management plugin

  # Django web server
  web:
    build:
      context: .
      dockerfile: DockerfileRpiNoConda
    hostname: web
    environment:
      - PATH=/opt/conda/bin:/usr/bin:$PATH
      - PYTHONUNBUFFERED=true
    volumes:
      - /home/pi/web/data:/ear_detection
    command: ./run_web.sh
    ports:
      - "8000:8000"
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - db

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: DockerfileRpiNoConda
    environment:
      - PATH=/opt/conda/bin:/usr/bin:$PATH
    command: ./run_celery.sh
    volumes:
      - /home/pi/web/data:/ear_detection
    ports:
      - "5555:5555"
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - rabbit
